#!/bin/bash
 
rm /tmp/screen.png
scrot /tmp/screen.png
convert /tmp/screen.png -scale 10% -scale 1000% /tmp/screen.png
 
if [[ -f $HOME/.config/screen-lock.png ]]
then
	# modify to fit your own system
        convert /tmp/screen.png $HOME/.config/screen-lock.png -geometry +2624+344 -composite -matte  /tmp/screen.png
        convert /tmp/screen.png $HOME/.config/screen-lock.png -geometry +704+344 -composite -matte  /tmp/screen.png
        echo "done"
fi
# dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop
# i3lock  -I 10 -d -e -u -n -i /tmp/screen.png
i3lock -e -u -n -i /tmp/screen.png
